apiVersion: v1
kind: Service
metadata:
  name: arctic-wolf-risk-manager-service
  namespace: prod
  labels:
    app: arctic-wolf-risk-manager
spec:
  type: NodePort
  selector:
    app: arctic-wolf-risk-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # You can customize this port if needed
